project:
  type: website

website:
  title: "Zahra Thabet"
  description: "Zahra Thabet's personal website"
  twitter-card: true
  search: false

  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - text: CV
        file: zahra_thabet_cv.pdf

format:
  html:
    theme:
      - default



