project:
  type: website
  output-dir: docs

website:
  title: "Carmen Strassle"
  description: "Carmen Strassle's personal website"
  twitter-card: false
  search: false

  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - href: talks.qmd
        text: Talks
 

format:
  html:
    theme:
      - default
    css: styles.css



